version: '3.3'

services:
    mongo:
        image: mongo:latest
        ports:
          - '27017:27017'
        volumes:
          - './data/mongo:/data/db'

    mongo-express:
        image: mongo-express:latest
        depends_on: 
            - mongo 
        ports:
            - '8081:8081'