version: '3.3'

services:
  react_native:
    build:
      context: ../app/
      args:
        - NODE_ENV=development
    container_name: react_native_app
    environment:
      - NODE_ENV=development
    tty: true
    ports:
      - '19000:19000'
      - '19001:19001'
      - '19002:19002'
      - '19003:19003'
      - '19004:19004'
      - '19005:19005'
      - '19006:19006'
    volumes:  
      - ../app:/app
    healthcheck:
      disable: true
  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - './data/mongo:/data/db'

  mongo-express:
    image: mongo-express:latest
    depends_on: 
      - mongo 
    ports:
      - '8081:8081'

    # webserver:
    #   image: nginx
    #   depends_on: 
    #     - mongo-express
    #   ports:
    #     - '80:80'
    #   volumes:
    #     - ./nginx:/etc/nginx/conf.d
    #     - ./data/public:/data
          